wordsnpages/Models/Company.cs
using System.ComponentModel.DataAnnotations;

namespace wordsnpages.Models
{
    public class Company
    {

        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        public string? StreetAddress { get; set; }
        public string? City { get; set; }
        public string? State { get; set; }
        public string? PostalCode { get; set; }
        public string? PhoneNumber { get; set; }
    }
}

wordsnpages/Controllers/CompanyController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using wordsnpages.Models;
using wordsnpages.Models.ViewModels;
using wordsnpages.Repositories.Interfaces;
using wordsnpages.Utilities;

namespace wordsnpages.Controllers
{
    [Authorize(Roles = SD.Role_Admin)]
    public class CompanyController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CompanyController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            // Retrieve all companies
            List<Company> objCompanyList = _unitOfWork.Company.GetAll().ToList();

            // Pass the list to the View method
            return View(objCompanyList);
        }

        // Combination of update and insert
        public IActionResult Upsert(int? id)
        {
            if (id == null || id == 0)
            {
                // Create
                return View(new Company());
            }
            else
            {
                // Update
                Company companyObj = _unitOfWork.Company.Get(u => u.Id == id);
                return View(companyObj);
            }
        }

        [HttpPost]
        public IActionResult Upsert(Company companyObj)
        {
            if (companyObj.Id == 0)
            {
                _unitOfWork.Company.Add(companyObj);
            }
            else
            {
                _unitOfWork.Company.Update(companyObj);
            }

            _unitOfWork.Save();
            TempData["success"] = "Company created successfully";
            return RedirectToAction("Index");
        }

        #region API CALLS

        [HttpGet]
        public IActionResult GetAll()
        {
            List<Company> objCompanyList = _unitOfWork.Company.GetAll().ToList();
            return Json(new { data = objCompanyList });
        }

        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var companyToBeDeleted = _unitOfWork.Company.Get(u => u.Id == id);
            if (companyToBeDeleted == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }

            _unitOfWork.Company.Remove(companyToBeDeleted);
            _unitOfWork.Save();

            return Json(new { success = true, message = "Successfully deleted" });
        }

        #endregion
    }
}

wordsnpages/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using wordsnpages.Models;
using wordsnpages.Models.ViewModels;
using wordsnpages.Repositories.Interfaces;
using wordsnpages.Utilities;

namespace wordsnpages.Controllers
{
    [Authorize(Roles = SD.Role_Admin)]
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment=webHostEnvironment;
        }

        public IActionResult Index()
        {
            // Retrieve all categories
            List<Product> objProductList = _unitOfWork.Product.GetAll(includeProperties: "Category").ToList();

            // Pass the list to the View method
            return View(objProductList);
        }

        //combination of update and insert
        public IActionResult Upsert(int? id)
        {

            ProductVM productVM = new()
            {
                CategoryList = _unitOfWork.Category.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }),
                Product = new Product()
            };
            if (id==null || id ==0)
            {
                //create
                return View(productVM);

            }
            else
            {
                //update
                productVM.Product = _unitOfWork.Product.Get(u => u.Id==id);
                return View(productVM);

            }
        }

        [HttpPost]
        public IActionResult Upsert(ProductVM productVM, IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                string wwwRootPath = _webHostEnvironment.WebRootPath;

                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                    string productPath = Path.Combine(wwwRootPath, @"images/product");

                    if (!string.IsNullOrEmpty(productVM.Product.ImageURL))
                    {
                        // Delete the old image only if ImageURL is not null or empty
                        var oldImagePath = Path.Combine(wwwRootPath, productVM.Product.ImageURL.TrimStart('\\'));

                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }

                    using (var fileStream = new FileStream(Path.Combine(productPath, fileName), FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }

                    productVM.Product.ImageURL = @"\images\product\" + fileName;
                }

                if (productVM.Product.Id == 0)
                {
                    _unitOfWork.Product.Add(productVM.Product);
                }
                else
                {
                    _unitOfWork.Product.Update(productVM.Product);
                }
                _unitOfWork.Save();
                TempData["success"] = "Product created successfully";
                return RedirectToAction("Index");
            }
            else
            {
                productVM.CategoryList = _unitOfWork.Category.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                });

                return View(productVM);
            }
        }

        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            List<Product> objProductList = _unitOfWork.Product.GetAll(includeProperties: "Category").ToList();
            return Json(new { data = objProductList });
        }

        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var productToBeDeleted = _unitOfWork.Product.Get(u => u.Id == id);
            if (productToBeDeleted==null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }

            var oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath, productToBeDeleted.ImageURL.TrimStart('\\'));

            if (System.IO.File.Exists(oldImagePath))
            {
                System.IO.File.Delete(oldImagePath);
            }

            _unitOfWork.Product.Remove(productToBeDeleted);
            _unitOfWork.Save();

            return Json(new { success = true, message = "Successfully deleted" });


        }
        #endregion
    }
}

wordsnpages/Views/Company/Delete.cshtml
@model Product
<div class="card shadow border-0 my-4">
    <div class="card-header bg-outline-secondary bg-gradient nl-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-primary py-2">Delete Product</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post">
            <input asp-for="Id" hidden />
            <div class="border p-3">
                <div class="form-floating py-2 col-12">
                    <input asp-for="Title" type="text" disabled class="form-control border-0 shadow" />
                    <label asp-for="Title">Product Title</label>
                </div>
                <div class="form-floating py-2 col-12">
                    <textarea asp-for="Description" type="text" disabled class="form-control border-0 shadow" > </textarea>
                    <label asp-for="Description" class="ms-2">Description</label>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="ISBN" type="text" disabled class="form-control border-0 shadow" />
                    <label asp-for="ISBN" class="ms-2">ISBN</label>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="Description" type="text" disabled class="form-control border-0 shadow" />
                    <label asp-for="Description" class="ms-2">Display Order</label>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="Author" type="text" disabled class="form-control border-0 shadow" />
                    <label asp-for="Author" class="ms-2">Author</label>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="ListPrice" type="text" disabled class="form-control border-0 shadow" />
                    <label asp-for="ListPrice" class="ms-2">List Price</label>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="Price" type="text" disabled class="form-control border-0 shadow" />
                    <label asp-for="Price" class="ms-2">Price</label>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="Price50" type="text" disabled class="form-control border-0 shadow" />
                    <label asp-for="Price50" class="ms-2">Price50</label>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="Price100" type="text" disabled class="form-control border-0 shadow" />
                    <label asp-for="Price100" class="ms-2">Price100</label>
                </div>

                <div class="row mt-3">
                    <div class="col-12">
                        <button type="submit" disabled class="btn btn-danger">Delete</button>
                        <a asp-controller="Product" asp-action="Index" class="btn btn-outline-secondary">Go Back</a>
                    </div>
                </div>
        </form>
    </div>
</div>

wordsnpages/Views/Company/Index.cshtml
@model List<Company>

<div class="card shadow border-0 my-4">
    <div class="card-header bg-outline-secondary bg-gradient nl-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-primary py-2">All Companies</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <div class="row  pb-3">
            <div class="col-6">
            </div>
            <div class="col-6 text-end">
                <a asp-controller="Company" asp-action="Upsert" class="btn btn-primary">
                    <i class="bi bi-plus-circle"></i>
                    Create New Company
                </a>
            </div>
        </div>

        <table id="tblData" class="table table-bordered" style="width:100%">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Address</th>
                    <th>City</th>
                    <th>State</th>
                    <th>Phone Number</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <!-- Data will be populated dynamically by DataTables -->
            </tbody>
        </table>
    </div>
</div>

@section Scripts {
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css">
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="~/js/company.js"></script>

    <script>
        $(document).ready(function () {
            $('#tblData').DataTable();
        });
    </script>
}

wordsnpages/Views/Company/Upsert.cshtml
@model Company

<div class="card shadow border-0 my-4">
    <div class="card-header bg-outline-secondary bg-gradient nl-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-primary py-2">@(Model.Id != 0 ? "Update" : "Create")  Company</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post" class="row" enctype="multipart/form-data">
            <input asp-for="Id" hidden />
            <div class="row">
                <div class="col-12">
                    <div class="border p-3">
                        <div class="form-floating py-2 col-12">
                            <input asp-for="Name" type="text" class="form-control border-0 shadow" />
                            <label asp-for="Name">Company Name</label>
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="StreetAddress" type="text" class="form-control border-0 shadow" />
                            <label asp-for="StreetAddress" class="ms-2">Address</label>
                            <span asp-validation-for="StreetAddress" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="City" type="text" class="form-control border-0 shadow" />
                            <label asp-for="City" class="ms-2">City</label>
                            <span asp-validation-for="City" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="State" type="text" class="form-control border-0 shadow" />
                            <label asp-for="State" class="ms-2">State</label>
                            <span asp-validation-for="State" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="PhoneNumber" type="text" class="form-control border-0 shadow" />
                            <label asp-for="PhoneNumber" class="ms-2">Phone Number</label>
                            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="PostalCode" type="text" class="form-control border-0 shadow" />
                            <label asp-for="PostalCode" class="ms-2">Postal Code</label>
                            <span asp-validation-for="PostalCode" class="text-danger"></span>
                        </div>
                        
                        <div class="row pt-2">
                            <div class="col-12">
                                @if (Model.Id!=0)
                                {
                                    <button type="submit" class="btn btn-primary">Update</button>
                                }
                                else
                                {
                                    <button type="submit" class="btn btn-primary">Create</button>
                                }
                                <a asp-controller="Company" asp-action="Index" class="btn btn-outline-secondary">Go Back</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
        </form>
    </div>
</div>

@section Scripts {
    @{
        // Client-side validation
        <partial name="_ValidationScriptsPartial" />
    }
}